In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\users\aayis\downloads\ai\venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aayis\downloads\ai\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\aayis\downloads\ai\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\aayis\downloads\ai\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.8 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.9 MB 1.8 MB/s eta 0:00:05
   ----- ---------------------------------- 1.3/9.9 MB 1.6 MB/s eta 0:00:06
   ------ --------------------------------- 1.6/9.9 MB 1.7 MB/s eta 0:00:05
   ------- -------------------------------- 1.8/9.9 MB 1.6 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.9 MB 1.6 MB/s eta 0:00:05
   ---------- ----------------------------- 2.6/9.9 MB 1.5 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.9 MB 1.5 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.9 MB 1.6 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.6 MB/s eta 0:00:04
   ---------------- ----------------------- 4.2/9.9 MB 1.6 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.9 MB 1.6 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.9 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.9 MB 1.6 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.9 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.9 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.9 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.6 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.9 MB 1.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.9 MB 1.6 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.9 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.9 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 1.6 MB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.6 MB/s  0:00:06
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
data={'Name':['A','B','C'],'Age':[20,33,45]}
df=pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   33
2    C   45

In [28]:
import pandas as pd
df=pd.read_csv('data.csv')
display(df)
print('head')
display(df.head())
print('tail')
display(df.tail())
print('info')
display(df.info())
display(df['city'],df['statezip'])

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

head

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

tail

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4595,2014-07-09 00:00:00,308166.666667,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,534333.333333,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,416904.166667,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,203400.000000,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,220600.000000,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

info
<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 647.0 KB

None

0       Shoreline
1         Seattle
2            Kent
3        Bellevue
4         Redmond
          ...
4595      Seattle
4596     Bellevue
4597       Renton
4598      Seattle
4599    Covington
Name: city, Length: 4600, dtype: str

0       WA 98133
1       WA 98119
2       WA 98042
3       WA 98008
4       WA 98052
          ...
4595    WA 98133
4596    WA 98007
4597    WA 98059
4598    WA 98178
4599    WA 98042
Name: statezip, Length: 4600, dtype: str